package iso8583

type PrimaryBitmapFlag uint64

const (
	SecondaryBitmap PrimaryBitmapFlag = 1 << iota
	PrimaryAccountNbr
	ProcessingCode
	TransactionAmt
	SettlementAmt
	CardholderBillingAmt
	TransmissionDateTime
	CardholderBillingFeeAmt
	SettlementConvRate
	CardholderBillingConvRate
	SystemsTraceAuditNbr
	LocalTxTime
	LocalTxDate
	ExpirationDate
	SettlementDate
	ConversionDate
	CaptureDate
	MerchantType
	AcqInstCountryCode
	PrimaryAccountNbrCountryCode
	FwdInstCountryCode
	PointOfSvcEntryMode
	CardSeqNbr
	NetworkInternationalId
	PointOfSvcCondCode
	PointOfSvcPINCaptureCode
	AuthIdResponseLen
	TransactionFeeAmt
	SettlementFeeAmt
	TransactionProcessingFeeAmt
	SettlementProcessingFeeAmt
	AcqInstIdentCode
	ForwardingInstIdentCode
	ExtendedPrimaryAccountNbr
	TrackIIData
	TrackIIIData
	RetrievalRefNbr
	AuthIDResp
	RespCode
	SvcRestrictionCode
	CardAcceptorTerminalID
	CardAcceptorIDCode
	CardAcceptorNameLocation
	AdditionalRespData
	TrackIData
	ExpandedAdditionalAmts
	AdditionalDataNational
	AdditionalData
	TxCurrencyCode
	SettlementCurrencyCode
	CardholderBillingCurrencyCode
	PersonalIDNumberData
	SecurityRelatedControlInfo
	AdditionalAmts
	IntegratedCircuitCardSystemData
	PaymentAccountData
	ReservedNationalUse57
	AuthorizingAgentInstID
	ReservedNationalUse59
	AdviceReasonCode
	PointOfSvcData
	IntermediateNetworkFacilityData
	NetworkData
	MessageAuthCode
)
